### ISSUE TITLE
Broken links to pdfs of specs

### ISSUE THREAD

**Issue by jmchapman** [input-output-hk/formal-ledger-specifications#230]
This link from the project readme currently 404s:

https://input-output-hk.github.io/formal-ledger-specifications/pdfs/cardano-ledger.pdf

The link to the html works though:

https://input-output-hk.github.io/formal-ledger-specifications/html/ledger/Ledger.PDF.html

**Comment by omelkonian** [comment]
A [previous commit of mine](https://github.com/input-output-hk/formal-ledger-specifications/commit/be18da610c045cda99266e8b7c8073efdb78d1f6) has caused this, the relevant changes being the different structure of the Haskell modules.

Upon further inspection of the CI logs:
- In step "Build static file", the following command runs:
```bash
for f in pdfs/*.pdf; do
    echo "<li><a href="$f">$(basename $f)</a></li>" >> index.html
done
```
Since we can see the .pdf files in the deployed website (in `index.html`), it means that pdfs/ contains both PDFs after the Nix builds.
In step "Add files", the command git add pdfs runs but there are no corresponding Git lines that indicate this, i.e. the following lines are missing / not printed:
```bash
 create mode 100644 pdfs/cardano-ledger.pdf
 create mode 100644 pdfs/midnight-example.pdf
 ```

**Comment by jmchapman** [comment]
Thanks Orestis, if this gets broken then it shouldn't pass CI.

A interim step might be to add "check that the PDFs build locally" to the PR checklist.

**Comment by omelkonian** [comment]
> Thanks Orestis, if this gets broken then it shouldn't pass CI.
> 
> A interim step might be to add "check that the PDFs build locally" to the PR checklist.

Actually the PDFs build both locally and in the CI machine, but somehow they do not get pushed to the `gh-pages` branch at the end of the CI run.
